//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEN341InstagramReplica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeDislikeList
    {
        public int ID { get; set; }
        public int LikeOrDislike { get; set; }
        public int UserId { get; set; }
        public int PostId { get; set; }
    
        public virtual UserPost UserPost { get; set; }
        public virtual User User { get; set; }
    }
}
