//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEN341InstagramReplica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkedAccount
    {
        public int ID { get; set; }
        public int Account1ID { get; set; }
        public int Account2ID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
