language: csharp
solution: SOEN341InstagramReplica.sln
install:
  - nuget restore SOEN341InstagramReplica.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release SOEN341InstagramReplica.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./MyProject.Tests/bin/Release/MyProject.Tests.dll
